using DSPoolGenerators.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static DSPoolGenerators.Utilities;

namespace DSPoolGenerators;

[Generator]
public class ManualSingletonGenerator : IIncrementalGenerator
{
    private readonly record struct TransformedInfo(string Name, string Namespace);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DSPoolManualSingletonAttributeConstants.IDENTIFIER,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (context, _) => Transform(context));

        context.RegisterSourceOutput(provider, Generate);
    }

    private static TransformedInfo Transform(GeneratorAttributeSyntaxContext context)
    {
        var poolDeclaration = (ClassDeclarationSyntax)context.TargetNode;

        return new(poolDeclaration.Identifier.ToString(), GetNamespace(poolDeclaration));
    }

    private static void Generate(SourceProductionContext context, TransformedInfo transformedInfo)
    {
        GenerateManualSingleton(context, transformedInfo);
    }

    private static void GenerateManualSingleton(SourceProductionContext context, TransformedInfo transformedInfo)
    {
        var sourceCode = $@"// <auto-generated />
using System;
using UnityEngine;

namespace {transformedInfo.Namespace}
{{
    public partial class {transformedInfo.Name}
    {{
        private static bool isInstanceInitialized;
        private static {transformedInfo.Name} instance;
        public static {transformedInfo.Name} Instance => instance ?? throw new NullReferenceException(""{transformedInfo.Name}_Singleton hasn't been initialized"");

        public static bool IsInstanceInitialized => isInstanceInitialized;

        public static void InitializeInstance({transformedInfo.Name} newInstance)
        {{
            if (newInstance == null) throw new NullReferenceException(""Can not initialize null instance for {transformedInfo.Name}_Singleton"");
            isInstanceInitialized = true;
            instance = newInstance;
        }}

        public static void DestroyInstance()
        {{
            isInstanceInitialized = false;
            instance = null;
        }}

#if UNITY_EDITOR
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        public static void ClearOnLoad() => DestroyInstance();
#endif
    }}
}}
";

        context.AddSource($"{transformedInfo.Namespace}.{transformedInfo.Name}.ManualSingleton.g.cs", sourceCode);
    }
}
