using DSPoolGenerators.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DSPoolGenerators;

[Generator]
public class PrefabPropertyGenerator : IIncrementalGenerator
{
    private readonly record struct TransformedInfo(string FullPrefabTypeName, string PoolName, string PoolDisplayName, string PoolNamespace);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DSPoolUsePrefabAttributeConstants.IDENTIFIER,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (context, _) => Transform(context));

        context.RegisterSourceOutput(provider, Generate);
    }

    private static TransformedInfo Transform(GeneratorAttributeSyntaxContext context)
    {
        var sm = context.SemanticModel;
        var attributeSyntax = (AttributeSyntax)context.Attributes[0].ApplicationSyntaxReference.GetSyntax();

        var attributeArgumentExpression = attributeSyntax.ArgumentList.Arguments[0].Expression;
        var prefabTypeInfo = sm.GetTypeInfo(((TypeOfExpressionSyntax)attributeArgumentExpression).Type);

        var poolDeclaration = context.TargetNode;
        var poolTypeInfo = sm.GetDeclaredSymbol(poolDeclaration);

        return new(
            prefabTypeInfo.Type.ToDisplayString(),
            poolTypeInfo.Name,
            poolTypeInfo.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
            poolTypeInfo.ContainingNamespace.ToDisplayString());
    }

    private static void Generate(SourceProductionContext context, TransformedInfo transformedInfo)
    {
        GeneratePrefabProperty(context, transformedInfo);
    }

    private static void GeneratePrefabProperty(SourceProductionContext context, TransformedInfo transformedInfo)
    {
        var sourceCode = $@"// <auto-generated />
namespace {transformedInfo.PoolNamespace}
{{
    public partial class {transformedInfo.PoolDisplayName}
    {{
        public {transformedInfo.FullPrefabTypeName} Prefab {{ get; set; }}
    }}
}}
";

        context.AddSource($"{transformedInfo.PoolNamespace}.{transformedInfo.PoolName}.PrefabProperty.g.cs", sourceCode);
    }
}
