using DSPoolGenerators.Common.StringBuilderUtilities;
using DSPoolGenerators.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using static DSPoolGenerators.Utilities;

namespace DSPoolGenerators;

[Generator]
public class SharedInstanceGenerator : IIncrementalGenerator
{
    private readonly record struct TransformedInfo(string Name, string Namespace, ClassDeclarationSyntax ClassDeclaration);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DSPoolSharedInstanceAttributeConstants.IDENTIFIER,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (context, _) => Transform(context));

        var perCandidate = classDeclarations.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(perCandidate, Generate);
    }

    private static TransformedInfo Transform(GeneratorAttributeSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.TargetNode;

        return new(classDeclaration.Identifier.ToString(), GetNamespace(classDeclaration), classDeclaration);
    }

    private static void Generate(SourceProductionContext context, (TransformedInfo transformedInfo, Compilation compilation) combined)
    {
        var (info, compilation) = combined;
        var semanticModel = compilation.GetSemanticModel(info.ClassDeclaration.SyntaxTree);

        if (semanticModel.GetDeclaredSymbol(info.ClassDeclaration) is not INamedTypeSymbol typeSymbol)
            return;

        string sharedName = $"Shared{info.Name}";
        string baseInstanceFullyQualifiedName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var sb = new CodeStringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0114");
        sb.AppendLine("#pragma warning disable CS0108");

        sb.AppendLine($"using UnityEngine;");
        sb.AppendLine();

        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();

        sb.AppendLine($"public static class {sharedName}");
        sb.AppendLine("{");
        sb.Indent();

        sb.AppendLine($"public static {baseInstanceFullyQualifiedName} _instance = new();");
        sb.AppendLine($"public static {baseInstanceFullyQualifiedName} Instance => _instance;");
        sb.AppendLine();

        sb.AppendLine("#if UNITY_EDITOR");
        sb.AppendLine("[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]");
        sb.AppendLine("public static void InitializeInstance() => _instance = new();");
        sb.AppendLine("#endif");
        sb.AppendLine();

        foreach (var method in GetAllPublicInstanceMethods(typeSymbol))
        {
            EmitMethod(sb, method);
            sb.AppendLine();
        }

        sb.Unindent();
        sb.AppendLine("}");

        context.AddSource($"{sharedName}.g.cs", sb.ToString());
    }

    private static IEnumerable<IMethodSymbol> GetAllPublicInstanceMethods(
        INamedTypeSymbol type)
    {
        for (
            INamedTypeSymbol? current = type;
            current is not null;
            current = current.BaseType)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is not IMethodSymbol method)
                    continue;

                if (method.MethodKind != MethodKind.Ordinary)
                    continue;

                if (method.DeclaredAccessibility != Accessibility.Public)
                    continue;

                if (method.IsStatic)
                    continue;

                yield return method;
            }
        }
    }

    private static void EmitMethod(
        CodeStringBuilder sb,
        IMethodSymbol method)
    {
        var returnType =
            method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var parameters = string.Join(
            ", ",
            method.Parameters.Select(p =>
                $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}"));

        var arguments = string.Join(
            ", ",
            method.Parameters.Select(p => p.Name));

        sb.AppendLine($"public static {returnType} {method.Name}({parameters})");
        sb.Indent();
        sb.AppendLine($"=> _instance.{method.Name}({arguments});");
        sb.Unindent();
    }
}
